### ISSUE TITLE
[ETHEREUM-CONTRACTS] Deterministic (network-wise) Wrapped-ERC20 Super Token Address for Simpler Discoverability

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1089]
Currently the Super Token factory can help anyone to issue new Wrapped ERC20 Super Tokens any time. It hinders the discoverability, for which Superfluid Finance's resolver mechanism is a sub-optimal patchwork for this limitation.

It needs not to be so, host contract could deem canonical wrapped ERC20 (in a sense that it uses super token logic  the host provides) something uniquely available per each network, deterministically generated, so that the discoverability problem goes away automatically.

## Technical notes

- A pre-built binary + CREATE2 could provide a decent technical solution.
  - Need to backward support resolver listed super tokens, and a lookup-table to cement "determined" super token address would be more practical way forward than CREAET2 (which in itself will be less useful) everything.
- Old mechanism should still be available, but new mechanism should be favored for listing criteria in superfluid finance's resolver.

**Comment by hellwolf** [comment]
Couple of quick notes per conversation:

- Need to backward support resolver listed super tokens, and a lookup-table to cement "determined" super token address would be more practical way forward than CREAET2 (which in itself will be less useful) everything.

More thoughts:

- Perhaps we could change the `createERC20Wrapper(Upgradability.NON_UPGRADABLE` semantic instead going forward, and add a new Upgradability.NON_UPGRADABLE_LEGACY if people still want to create their wrapper anyhow.

**Comment by d10r** [comment]
Combination of forward-looking and backward looking:

### forward-looking
Use CREATE2, with the address of the underlying being (part of) the nonce. By having `createERC20Wrapper` deploy that way, we implicitly add protection against duplicate deployments (deploying additional wrapping SuperTokens would require a more conscious action -> deployment of a custom SuperToken).  
We should add a method for determining the would-be SuperToken address of a not-yet-deployed SuperToken (default wrapper) - with the guarantee limited to: this would be the address if the SuperToken is deployed with the current protocol version.

### backward-looking
In order to accomodate legacy (previously deployed SuperTokens) and make changes in the deployed bytecode (proxy) painless, addresses of canonical wrappers are looked up, not calculated. Meaning on deploy, the address needs to be added to a lookup table.  
In order to have previously deployed SuperTokens in that table, we need to once provide a hardcoded list of such pre-existing SuperTokens.
