### ISSUE TITLE
[Deployer Whitelisting Request] : StreamableCouncilNFT 

### ISSUE THREAD

**Issue by godzillaba** [superfluid-finance/protocol-monorepo#1154]
**Describe the SuperApp:**

An NFT contract that takes an incoming superfluid stream, splits it evenly, and makes outgoing streams to NFT holders. There will be a maximum of 8 holders per NFT. We will deploy multiple instances of the NFT contract.

**Network will be deployed?:**

Polygon Mainnet

**Deployer address:**

0xBFb1c7BE402eC0D289fA25db4C544718D5CF1Df2

**Link of repo of the contract to be deployed:**

The repo is currently private, if we could invite you all to the repo that would be great! If not we can also probably make the repo public. 

**Contact info for developer:**

henry@telco.in

**Notes:**

We have one contract called `StreamableCouncilNFT` which is where all the fun superfluid logic is.

**Comment by hellwolf** [comment]
@godzillaba could you add @hellwolf @d10r @0xdavinchee @ngmachado to the repo.

**Comment by godzillaba** [comment]
i invited you all

**Comment by d10r** [comment]
Hi @godzillaba 
I took a look at the contract, here's a few comments:

As you're likely aware of, the for-loops in [_updateOutFlow](https://github.com/telcoin/superfluid-nft/blob/master/contracts/StreamableCouncilNFT.sol#L4836) could run out of gas if there's too many tokens to be iterated over, leading to the App being [jailed](https://docs.superfluid.finance/superfluid/developers/super-apps/super-app#super-app-rules-jail-system).  
While only the contract owner could bring the contract into such a "broken configuration" by minting "too many" tokens, I think it would be prudent to enforce a limit making this impossible in the contract.  
I recommend to also put a comment in front of that loop highlighting that hazard and how it's mitigated.

As for [this comment](https://github.com/telcoin/superfluid-nft/blob/master/contracts/StreamableCouncilNFT.sol#L4902): if no flow exists, this will just return a zero flowrate.

Minor detail: some error messages in "require" statements are prefixed with the name of the contract they were copied from, e.g. `require(_isSameToken(superToken), "RedirectAll: not accepted token");` - I suggest to change that.

**Comment by godzillaba** [comment]
Hi @d10r 
Thanks for the feedback! I just made those changes you suggested.

**Comment by d10r** [comment]
I see you put the limit at 10. Not sure if that fits the [callback gas budget of 3M](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/Superfluid.sol#L65).  
Also don't make it too tight, because gas costs for the operations involved aren't constant long term, can change with protocol upgrades or even hardforks of the base protocol changing opcode pricing.

One rather simple optimization you could do which I think would yield significant gas savings:
Instead of first deleting and then creating all flows in `_updateOutFlow_` you could also use `updateFlow`.  
An example for such a logic can be found in the [here in the CFAv1Forwarder contract](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/utils/CFAv1Forwarder.sol#L282).

**Comment by godzillaba** [comment]
I revised the limit to 8 and made the recommended changes to `_updateOutflow`. The new work is on the `gas` branch. I have a `beforeAgreementCreated` function that doesn't seem to be getting called in my tests. I was going to add a check there that makes sure only one incoming stream can exist at a time. instead i put the check in `_updateOutflow`.

**Comment by godzillaba** [comment]
I revised the max supply to 8 and made those changes `_updateOutflow`. It seems like the `afterAgreementTerminated` callback uses about 2.7M gas when there are 8 NFTs. `afterAgreementCreated` and `afterAgreementUpdated` use less. The new work is on the `gas` branch. I used events to check gas usage in the tests which I would remove before production.

**Comment by godzillaba** [comment]
hi @d10r , just checking in here. not trying to be pushy or anything :)

**Comment by d10r** [comment]
@hellwolf the gov action is ready to be signed.

@godzillaba thx for the reminder.
One more comment about gas: 2.7M is pretty narrow, be careful. It may actually be more on mainnet due to NFTs being minted to flow receivers on creation of new flows. That's something which could be mitigated by updating the flowrate instead of deleting and creating flows.

Once the gov action is signed (there'll be a notification here), the provided deployer address has permission to deploy SuperApps for the next 6 months. The registrationKey is "k1".

**Comment by hellwolf** [comment]
@godzillaba please heed to @d10r 's advice, and good luck!

![image](https://user-images.githubusercontent.com/186660/203390243-fe96e740-454b-4c3a-b7cb-d8000b0b7bc0.png)

**Comment by godzillaba** [comment]
thank you!
