### ISSUE TITLE
[SDK-CORE] `@nomiclabs/hardhat-ethers/types` is in published package but not specified as a dependency

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#1174]
If any consumer uses tsconfig's `skipLibCheck=false` and they don't have `@nomiclabs/hardhat-ethers/types` installed themselves then it starts failing:
![image](https://user-images.githubusercontent.com/10894666/202734427-68923159-7b4f-4b0e-90a0-fda0b1bda734.png)

I think the root of the issue is the monorepo & yarn & CI set-up. As far as I can tell, when something is building in the pipeline then hard to say whether it got the dependencies from the root of the repo (which might come from another package), whether it used a local symlink, whether a devDependency is exposed in the final output, etc.

**Comment by hellwolf** [comment]
>  As far as I can tell, when something is building in the pipeline then hard to say whether it got the dependencies from the root of the repo (which might come from another package), whether it used a local symlink, whether a devDependency is exposed in the final output, etc.

That's indeed something we could improve. Not sure what's the existing solution yet. If anyone knows, do suggest. Otherwise, we could also do a new lint step as our own solution.

Usually we use "lerna" to update versions to avoid the situation that a monorepo package would not use local version of another monorepo package. But if that "lerna" step had a mistake, it is not discoverable.

**Comment by hellwolf** [comment]
This will go to the nexgen tooling improvement plan.
