### ISSUE TITLE
[SDK-CORE] List of SDK-Core Feature Requests

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1230]
## Motivation

It may be a good time to go back to basics and reminding ourselves what the core purpose/intention of the SDK-Core is:
- is it meant to be a direct simple wrapper around the contracts?
- or maybe an abstraction to simplify and reduce as much complexity on the surface for developers.

I would argue it is the latter as there is not much value in the first case (there are so many tools that can do this).

The purpose of a software development kit is to package software in an opinionated way so that external developers can interface with the underlying software without having to fully understand the minutiae. 

We had our own opinionated ideas of what the purpose/intention of SDK-Core was and still have some ideas, but it's far more important that we utilize feedback from external devs via devx on what motivates them to use it (why they use it) and also what they would like to see in the future.

## Possible Ideas
- ~Surfacing `createFlow`, `transfer`, etc. at the top level of the framework to reduce mental overhead regarding what `host`, `cfav1`, `idav1`, etc. mean~ **Deemed to be opposing our token centric interface narrative** 
- allowing users to pass in a provider/signer upon initialization **which will be used**, the distinction here is the usage of the passed provider
  - important to prevent shooting self in foot with a check if provider/signer chainId is equal to the expected chainId
- another route would be to initialize SDK-Core with the Superfluid RPC, we would query and prepare all transactions through our own RPCs and still allow users to pass their wallet for signing
- fix interface types especially surrounding flow creation, the SDK-Core can be simplified by mapping exactly what we expect to each type
- No `gasLimitMultiplier` when executing `batchCall`/`forwardBatchCall`
  - We should also have functions such as `estimateGas`, `getPopulatedTransactionPromise` for both the `BatchCall` class and the `Operation` class, allowing explicit separation of: signing, gas estimation and transaction broadcasting
- [BREAKING] Change the `Operation.exec(signer)` API syntax to no longer be the default, instead allow `await framework.createFlow(params)` which returns a transaction receipt (what `contract.someWriteFunc()` would return)
  - Provide alternative param property OR function which still has batch call support.
- [BREAKING] Functional SDK-Core (@kasparkallas you mentioned this to me a while back)-if we are considering making some breaking changes, it may be a good place to consider making changes to this as well.

## Main TODOs 
- [ ] Highlight the token-centric interface and no longer create operations by default, operations can still be created for batchCall's though
- [ ] Pass in a provider/signer and use this throughout its lifetime, allow users to override this when executing or at any point.
  - [ ] Must check if provider chainId is same as desired chainId

cc @tokdaniel @saflamini @kasparkallas (if the implementation changes, this will impact SDK-Redux)

**Comment by saflamini** [comment]
@0xdavinchee this is a good idea to look at. When we release the new SuperTokenLibrary, we'll have an opportunity to start recommending that all users begin adopting a 'token centric' approach to building on Superfluid, even before we change the underlying protocol to reflect our ERC20x plans. We should aim for consistency with the SDK (but I think most of this work can be done via communication about best practices for using our tooling, rather than making breaking changes to the tooling itself).

A couple of thoughts:

1) I actually don't think that we need to surface createFlow, transfer, etc on the Framework object directly. I think we can recommend that developers use these functions on the token object though. For example:

`daix = await sf.loadSuperToken('DAIx');`
`daix.createFlow(....)`

2) I like this idea of removing the required Operation.exec syntax. This is useful for batch calls, but quite different from what people are used to with libraries like ethers. 

3) What is functional SDK core @0xdavinchee ?

**Comment by 0xdavinchee** [comment]
> 3) What is functional SDK core @0xdavinchee ? 

My details on this is fuzzy, this idea was Kaspar's. It definitely involves discussions with you though as it'll change the API quite significantly.
