### ISSUE TITLE
[ETHEREUM-CONTRACTS] Fix the staging protocol deployment (protocol_release_version = "master")

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1633]
~~Staging protocol deployment (`PROTOCOL_RELEASE_VERSION=master`) is used solely for incremental deployment testing purpose, based of the canary/dev branch.~~

Currently it uses avalanche-fuji, we had broken it a while ago and we don't understand why yet.

**Comment by hellwolf** [comment]
Bumping up severity because the canary build is broken for too long due to this.

**Comment by hellwolf** [comment]
Changing the scope, we now target to fix the current avalanche-fuji staging protocol deployment instead.

The issue currently is that the avalanche-fuji staging protocol deployment is of GDA branch, and hence not upgradable through the canary CI process anymore.

We can simply do another reset and move on.

**Comment by philipandersson** [comment]
@hellwolf @d10r Is this still relevant or can we close?

**Comment by d10r** [comment]
still relevant

**Comment by d10r** [comment]
https://github.com/superfluid-finance/protocol-monorepo/pull/1742 waiting to be merged

**Comment by d10r** [comment]
This keeps failing in CI, see e.g. https://github.com/superfluid-finance/protocol-monorepo/actions/runs/6982296547/job/19002154805

Likely caused because of individual RPC calls failing.
When executing the same command locally, the deploy-framework part usually succeeds. When going through the token deployment, it eventually fails. That is because - as was previously found out - the way this is implemented, multiple truffle instances are created without previous ones being destroyed, with every additional truffle instance adding to the number of requests being done in the background, eventually overwhelming the RPC with dozens of (redundant) requests per second. (a good PM tool would make it easy now to find and reference an issue where this was documented in more detail...).

With truffle being deprecated, it's probably not worth investing much time in this. 
I don't currently have an idea for how to mitigate, but will keep in the back of my mind.
