### ISSUE TITLE
[PROTOCOL-OPS] Safe Governance Missing Verified Contracts Visualization

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1657]
Currently cumbersome to sign multisig operations which don't have clear decoding
Even more critical when considering adding external signers

**Comment by d10r** [comment]
https://github.com/safe-global/safe-transaction-service/issues/1653

**Comment by d10r** [comment]
[Den](https://docs.onchainden.com/overview/den) now has support for Base, [also for the other networks SF is deployed to, except of Celo](https://docs.onchainden.com/overview/den).

That's what a gov tx looks like:
https://app.onchainden.com/safes/base:0xd8a05f504b5ce16183d3e1e16fd6a365a8db53da/transactions/0xb7853a2e2dd82117b3fa440e394d311398740564a9809ba158ac1964726d9554

**Comment by hellwolf** [comment]
Can you take a screenshot? I can't atm without signing a signature with the key.

So is it correct to say that the suggested steps is:

- copy the gov tx txhash
- use app.onchainden.com url format to decode that tx? (how exactly)

**Comment by d10r** [comment]
you should see this with the link above:
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/5479136/6c552107-caf7-42dc-8924-33217cd4c17b)
The rendered method name and params are auto-generated from the contract source which I assume it fetches from etherscan and/or sourcify.
The _description_ it asks you to login for is additional data which could be added by a Safe signer via Den itself. I didn't yet try that. But that's "trust me bro" kind of information anyway, for verification the extraction of method name and params is much more helpful imo. If you click the method, it will also show its sourcecode:
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/5479136/e81d1f19-3008-4bce-9837-098584a6effd)

In order to get that view, one can either manually construct the URL, e.g.
https://app.safe.global/home?safe=base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da
becomes
https://app.onchainden.com/safes/base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da

Or go to https://app.onchainden.com, sign in with your signer account and the Safes it co-owns will be shown.

**Comment by hellwolf** [comment]
Ah, okay. I will validate this next time I do it.
