### ISSUE TITLE
[SUBGRAPH BUG] flowDistributionUpdatedEvents not being picked up by the graph

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/protocol-monorepo#1747]
**Describe the bug:**
A clear and concise description of what the bug is. What is the data you are having issues with?

**Subgraph endpoint:** [e.g. https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-goerli]
https://api.thegraph.com/subgraphs/name/superfluid-finance/protocol-v1-optimism-goerli

**Query:**
e.g. 
```
query MyQuery {
  flowDistributionUpdatedEvents {
    id
  }
}
```

**Expected data:**
I would expect to see more than 1 flowDistributionUpdated events, e.g.
https://goerli-optimism.etherscan.io/tx/0xa00990ffad4bd6c2482ccf3070a02c9be21828acc11e3075119e84f5991b59bc#eventlog
https://goerli-optimism.etherscan.io/tx/0xdb60cd7725c48ee8dd6f72ccfc38233bcc8631791fca0e2a9929dfdf76d808ba#eventlog
https://goerli-optimism.etherscan.io/tx/0xdb60cd7725c48ee8dd6f72ccfc38233bcc8631791fca0e2a9929dfdf76d808ba#eventlog

**Actual data:**
A clear and concise description of what is incorrect with the data or paste the returned data (within reason).
Only one distribution updated event is shown
![Screenshot 2023-11-14 at 12 20 13](https://github.com/superfluid-finance/protocol-monorepo/assets/77115130/ba96a1b6-cf35-4183-915f-4923237c52f1)

**Additional context:**
This wallet has got a bunch of events https://goerli-optimism.etherscan.io/address/0xdc305dd2551a8d331d372460ed72e6ad846f435a

**Comment by 0xdavinchee** [comment]
attempting to redeploy subgraph: https://github.com/superfluid-finance/protocol-monorepo/actions/runs/6865195493

it is quite a confusing issue otherwise

**Comment by 0xdavinchee** [comment]
looks like the optimism-goerli subgraph is quite outdated, I would reckon that this is related to the issue.

**Comment by hellwolf** [comment]
do we redeploy?

**Comment by 0xdavinchee** [comment]
I tried to but there was an issue in `buildNetworkConfig.ts` due to inconsistencies between what we've decided to go with in terms of canonical names in `shortName` or `name` in metadata.

Addressing this root issue, once and for all here: https://github.com/superfluid-finance/protocol-monorepo/pull/1748.

Placing the canonical name in metadata once and then we can just forget about it and use the canonical name instead.

**Comment by d10r** [comment]
Agree, we need to handle this mappings in metadata.
The numerical chainId is the only deterministic and unique identifier we can rely on across the ecosystem.
Going forward we should try to minimize the amount of non-SF-specific information we need to manually maintain in metadata in order to keep maintenance overhead of shuffling networks low.  
Can be done by adding a postprocessing step to metadata (or just add to the existing build script) which pulls in relevant metadata provided by others, e.g.  https://github.com/wagmi-dev/viem/tree/main/src/chains/definitions , and merges that with SF-specific metadata.

**Comment by d10r** [comment]
fixed and re-synced

**Comment by 0xdavinchee** [comment]
https://github.com/superfluid-finance/protocol-monorepo/issues/1747#issuecomment-1816089319
