### ISSUE TITLE
[SUBGRAPH BUG] Investigate why total supply is mapped wrong for ALEPH token on Avalanche

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#1815]
**Describe the bug:**
A clear and concise description of what the bug is. What is the data you are having issues with?

**Subgraph endpoint:** https://console.superfluid.finance/subgraph?_network=avalanche-c

**Query:**
```graphql
{
  tokenStatistic(id: "0xc0fbc4967259786c743361a5885ef49380473dcf") {
    totalSupply
    token {
      symbol
    }
  }
}
```

**Expected data:**
Token supply: 500000000000000000000000000

**Actual data:**
Token supply: 1000000000000000000000000000

**Additional context:**
Slack thread: https://superfluidhq.slack.com/archives/C03DP3AQH2A/p1706026485881119

**Comment by 0xdavinchee** [comment]
cc @kasparkallas 

Important things to note:
1. There are only two place `tokenStatistic.totalSupply` is incremented:
  a. `getOrInitSuperToken` is called the very first time when the entity for the token hasn't been created yet and 
  b. `handleMinted`.
2. The `Minted` event is emitted after the `CustomSuperTokenCreated` if we base it off `logIndex`.

After a quick investigation, it appears that the issue here is most likely related to `getInitialTotalSupplyForSuperToken` in `getOrInitSuperToken`. This function is called in `handleCustomSuperTokenCreated` before `handleMinted` is called (if we look at `logIndex`).

An RPC call in `getInitialTotalSupplyForSuperToken` is triggered to get and set total supply and there is only one minted event, so this must be the culprit.

Query:
```
{
  customSuperTokenCreatedEvents(
    where: {token: "0xc0fbc4967259786c743361a5885ef49380473dcf"}
  ) {
    blockNumber
    logIndex
  }
  mintedEvents(where: {token: "0xc0fbc4967259786c743361a5885ef49380473dcf"}) {
    blockNumber
    logIndex
  }
  tokenStatistic(id: "0xc0fbc4967259786c743361a5885ef49380473dcf") {
    totalSupply
    token {
      symbol
    }
  }
}
```

Output:
```
{
  "data": {
    "customSuperTokenCreatedEvents": [
      {
        "blockNumber": "40737288",
        "logIndex": "6"
      }
    ],
    "mintedEvents": [
      {
        "blockNumber": "40737288",
        "logIndex": "11"
      }
    ],
    "tokenStatistic": {
      "totalSupply": "1000000000000000000000000000",
      "token": {
        "symbol": "ALEPH"
      }
    }
  }
}
```
