### ISSUE TITLE
[JS-SDK] Create type information files (d.ts files)

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#360]
## Synopsis

While JS-SDK in plain javascripts, it is a step forward for the typescript developers to have the type information for all the classes JS-SDK implements.

## Spec/ACs

- These classes/helpers have already JS doc that serve as reference for the type declarations:
  - Framework
  - CFAHelper
  - IDAHelper
  - User
  - batchCall
- Follow the convention of other projects, create d.ts file for each files separately
- Create an example project under examples that use typescript and the SDK.
  - Demonstrate that type information provide "Intelligent" in the IDEs.
- For external entities, apply best effort to include their type information, or use wildcard "any" type

## References

- https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

## Bounty Information

Bounty size: $ 800

**Comment by rootulp** [comment]
@hellwolf thanks for creating this issue! I think TypeScript definitions will significantly improve developer experience when using `js/sdk`. Is the team open to progressively adopting TypeScript for `js-sdk`? I think generating TypeScript definition files from JSDoc is a viable temporary solution but JSDoc comments with types are prone to becoming out of date or inaccurate.

If `js-doc` progressively adopted TypeScript, we can improve the developer experience for developers who work on `js-sdk` as well as consumers of `js-sdk`. Additionally, TypeScript definitions produced from TypeScript source are much less likely to contain inaccurate types because a type error will fail at compile time. Types generated from JSDoc makes no such guarantee.

**Comment by hellwolf** [comment]
@rootulp understood. we are taking on js-sdk to next step very soon, and typescript is certainly part of the consideration and very demanded one.
