### ISSUE TITLE
Superfluid Governance II - MultiSig upgradable governance

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#399]
## Requirements

- [x] Upgradable governance
- [x] Allow app-registration whitelisting using factory address (registerAppByFactory)
- [ ] Create the stand-by governance on polygon and xdai
  - Make sure the local binary is built up to date
  - Use "npx truffle run etherscan" to validate the contract on polygonscan (need ETHERSCAN_API_KEY)
  - Do similar thing for xdai
  - Port the existing configurations
    - trusted forwarders (biconomy, maybe GSN)
    - CFA liquidation period
- [ ] Transfer the standby governance to multisig protocol admin
- [ ] Transfer governance from "Superfluid Governance I" to "Superfluid Governance II"
  - [ ] Document the transition in https://github.com/superfluid-finance/protocol-monorepo/wiki/Governance

**Comment by d10r** [comment]
use `ISuperfluidGovernance.replaceGovernance(ISuperfluid host, address newGov)` (?)

What is `deployer address`?

gov has a kv store for config items.  
Current items (see library `SuperfluidGovernanceConfigs` in `Definitions.sol`): 
* reward address
* CFAv1 liquidation period
* trusted forwarders
* SuperAll whitelisting secret keys

For upgradability, I can probably just implement the `UUPSProxiable` interface.  
Should the contract also have a `NON_UPGRADABLE_DEPLOYMENT` toggle like the host contract?  

Figure out an efficient dev workflow for working on framework contract.

**Comment by d10r** [comment]
current projects with the need to register SuperApps:
Ricochet Exchange: uses an EOA, but would like to reuse a secret for multiple contracts
Creaton: uses a factory contract

registerAppWithKey -> key marked as used

shouldn't be (only) key based anymore.
we can also remove the use of` tx.origin` (replace with `msg.sender`, that would facilitate Optimism compatibility (see https://github.com/superfluid-finance/protocol-monorepo/issues/395)

**Comment by d10r** [comment]
For adding upgradability to `SuperfluidGovernanceBase`, I use `SuperTokenFactory` and `AgreementBase` as a reference.

Why is there a return statement [here](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/agreements/AgreementBase.sol#L32)?

In `SuperTokenFactory` and `Superfluid`, the method `initialize` is placed in the (comment based) section `UUPSProxiable`, but afaik doesn't belong to its interface.

**Comment by d10r** [comment]
First shot at upgradability:
https://github.com/superfluid-finance/protocol-monorepo/commit/8d2e3b3b14de

issues encountered:
* when implementing UUPSProxiable in the Base classe (as recommented), how to do permissioning of `updateCode()`? All privileged methods in that contract take a host as argument which is forwarded to the virtual method `_requireAuthorised`.  
I could add that as param to updateCode too and delegate to an internal only `updateCode(address)`. but is that a good idea?
* subclass `SuperfluidOwnableGovernance` implements `Ownable` which has a private field `_owner` set in the constructor. When used in a proxy context, the owner is 0 (bcs it's set in the logic contract, not the proxy contract). That's why tests currently fail. Not sure how to best deal with that.

**Comment by hellwolf** [comment]
```
1. CREATE SuperfluidGovernanceIIProxy -> proxy (setOwner)
2. create SuperfluidGovernanceII -> gov2
3. proxy.initializeProxy(gov2)
4. (optional) LogicContract(proxy).intialize(...args)

- contract SuperfluidGovernanceIIProxy is Ownable, UUPSProxy
- contract SuperfluidGovernanceII is Ownable, UUPSProxiable, SuperfluidGovernanceBase
```

**Comment by hellwolf** [comment]
rename SuperfluidOwnableGovernance.test.js  to SuperfluidGovernanceII.test.js

**Comment by hellwolf** [comment]
test the double initialization and ownable protection too
