### ISSUE TITLE
Token Listing is not WORKING for NORI token

### ISSUE THREAD

**Issue by msoni89** [superfluid-finance/protocol-monorepo#559]
Listing of Nori token using github-ci script failed due to an error.

https://www.notion.so/superfluidhq/List-a-new-token-1b45a826447f4c58a46b7873a99ab79d
https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1687395337
https://mumbai.polygonscan.com/address/0x3325e2987D4C0804A020b2Ec4F9BcB3DD50014EE 

![image](https://user-images.githubusercontent.com/65469737/149137584-8f08644b-a23b-4b72-9efe-bf0f2cf2b1f4.png)
![image](https://user-images.githubusercontent.com/65469737/149137622-33c8827a-7180-4cf3-b70c-c81a3ddde69a.png)

**Comment by d10r** [comment]
Looks like the token contract at 0x3325e2987D4C0804A020b2Ec4F9BcB3DD50014EE doesn't implement `UUPSProxiable.proxiableUUID()`.  
@msoni89 do you know how this token was deployed?

@miao `ISuperToken` doesn't require `UUPSProxiable`. Is it safe to assume (as [the listing script does](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/scripts/resolver-list-super-token.js#L52)) that every SuperToken implements it?

**Comment by msoni89** [comment]
@kobuta23 Please check didi question, is there any way to reach out to the deployer?

**Comment by jaycenhorton** [comment]
Hello @msoni89 , @d10r!

Not sure I understand the issue here. Does the token contract I deploy need to to implement `proxiableUUID`? If it's useful, [here is the code for the NORI contract](https://github.com/nori-dot-eco/contracts/blob/5b975e93f4aa7778530cae251ed64c2e3d8b89a3/contracts/NORI.sol)

**Comment by d10r** [comment]
This seems to be some custom construction.  
The token contract is a [TransparentUpgradableProxy](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/transparent/TransparentUpgradeableProxy.sol) according to [PolygonScan](https://mumbai.polygonscan.com/address/0x3325e2987d4c0804a020b2ec4f9bcb3dd50014ee#code).

Looking at the [creation tx in tenderly](https://dashboard.tenderly.co/tx/mumbai/0x0b7a19042bb1309f1b0e6e9593eb002efb464933f49b97195edc55b50bbc9c08), I'd guess [0x3c5d3e20ab495ecee10b4e6eead04dd21d780b98](https://mumbai.polygonscan.com/address/0x3c5d3e20ab495ecee10b4e6eead04dd21d780b98) to be the implementation contract. No code there, so it's just a guess. The consumed gas of ~2.5 in [its creation tx](https://mumbai.polygonscan.com/tx/0x913a2a10edfea1cf72d3165f2abd9ada9ee052e9f2caf85c397172e6cf2b1d9f) point at a rather complex contract, could be SuperToken logic. Also, I can instantiate that contract in a truffle console and call methods like `name()`.

It looks to me like the token contract itself is malfunctioning. While same ERC20 methods work (e.g. `name()` and `totalSupply()`), everything else fails, e.g. `getUnderlyingToken() reverts`. It's hard to tell if this is because of the proxy or the implementation logic. Anyway, I don't think we can do anything about it without more information.

**Comment by d10r** [comment]
@jaycenhorton thx for the link, will check.

**Comment by d10r** [comment]
@jaycenhorton I took a look at the source.  
NORI.sol isn't a SuperToken.  
I recommend you check out the recently added docs at https://docs.superfluid.finance/superfluid/protocol-developers/guides/super-tokens for an overview of SuperToken types and how to deploy.
