### ISSUE TITLE
CFAv1Library.sol Solidity compiler version

### ISSUE THREAD

**Issue by 0xYao** [superfluid-finance/protocol-monorepo#619]
Most contracts in Superfluid use the `>=0.7.0` Solidity compiler version, but `CFAv1Library.sol` uses `^0.7.0`. This is a problem because the it is incompatible with the latest `@openzeppelin` contracts which use `^0.8.0`. I suspect there are more packages that have updated the compiler version to 0.8.x already.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@superfluid-finance/ethereum-contracts/contracts/apps/CFAv1Library.sol b/node_modules/@superfluid-finance/ethereum-contracts/contracts/apps/CFAv1Library.sol
index 13e4b95..519ceb9 100644
--- a/node_modules/@superfluid-finance/ethereum-contracts/contracts/apps/CFAv1Library.sol
+++ b/node_modules/@superfluid-finance/ethereum-contracts/contracts/apps/CFAv1Library.sol
@@ -1,5 +1,5 @@
 //SPDX-License-Identifier: AGPLv3
-pragma solidity ^0.7.0;
+pragma solidity >=0.7.0;
 pragma experimental ABIEncoderV2;
 
 import {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hellwolf** [comment]
Thanks @0AlexZhong0! Good idea.

@0xdavinchee let's do it

**Comment by hellwolf** [comment]
Piggybacked this into #595

**Comment by d10r** [comment]
projects using this still need to have a 0.7 compiler configured, bcs ISuperToken pulls in openzeppelin v3 contracts with pragma <0.8. Can be worked around by listing multiple compilers, e.g. in `hardhat.config.js`
```
module.exports = {
  solidity: "0.8.4",
  solidity: "0.7.6"
};
```

**Comment by hellwolf** [comment]
I see

TO make interface files >= 0.7 compatibility an requirement, we could also copy IERC20, IERC777 definitions over.

Unless solidity has some sort of c-style preprocessor built-in, so that we could import both versions of OZ in package.json (e.g. https://reactgo.com/npm-install-same-package-multiple-versions/)  per different solidity, but I don't think so (at least wouldn't be 0.7.x compatible in the first place.
