### ISSUE TITLE
[SUBGRAPH] Validate Balance-centric Subgraph

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#728]
**Describe the issue:**
Try building a balance-centric subgraph, per the below design.
![image.png](https://images.zenhubusercontent.com/5a045ea68a75884b9086bebc/99a74fe8-9a9b-456c-9783-84ef32671b8a)

The intended benefits are as follows:
- Web3 calls are not required for querying balance
- Notifications and automation backend (platform) can be more minimal
- Data dashboards for solvency health are simpler to produce
- Improve data querying for human readability
- Improve data querying for data visualization

**Timebox:**
This spike should be capped at 3 days and reviewed at the end of the spike.

**Additional context:**
- A primary concern for this subgraph is that it may create DDOS attack vectors.

**Comment by hellwolf** [comment]
Not sure I like it being called "Solvency-centric", will find better naming of this during the investigation.

**Comment by kasparkallas** [comment]
Updated to a more granular diagram:
![image](https://user-images.githubusercontent.com/10894666/163156953-b77a9936-981d-440c-a2fe-2099e51dfff9.png)

Very notable changes:
* IndexUnitsUpdatedEvent corrected to IndexUpdatedEvent
* Added missing SubscriptionDistributionClaimedEvent & SubscriptionApprovedEvent

**Comment by kasparkallas** [comment]
Addition to the latest diagram:
![image](https://user-images.githubusercontent.com/10894666/163178263-c08d29e5-4e98-47fd-9b16-efa01bceb9ab.png)

* Added missing AgreementLiquidatedByEvent & AgreementLiquidatedV2Event

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/163341732-0cfa4281-1237-4cca-83b6-28d4f609f619.png)

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/164516085-9929ec4c-9dc0-468a-98e1-2eb98b2c95ab.png)

![image](https://user-images.githubusercontent.com/65469737/164516709-fd76c3e7-d35f-482b-b7ef-03b11fdd1a4d.png)


Failed to distribute reason
`**ERRO Subgraph failed with non-deterministic error: failed to process trigger**: block #11032 (0x7803…db85), transaction ec1963108703eb7038d81ece686410008e3d0ee146c59776b8d0b2560e0851c0: **Gas limit exceeded. Used: 10000025994697**	wasm backtrace:	    0: 0x4ac5 - <unknown>!src/mappingHelpers/getOrInitAccountTokenBalance	    1: 0x6c89 - **<unknown>!src/mappings/idav1/createIndexSubscribedEntity**`

Total record: 10000
Run time: 4.5 hours, Injection: 3 hours, and indexing completed after 1.5 hours of all transactions.
Transactions: Created Index, updateSubscriptionUnits (Batch of 10), approveSubscription (in loop) and distribute.

**Comment by kasparkallas** [comment]
The Graph Node has an internal concept of _gas_ to measure the resources used up by the event handler (mapper). This "gas" is in no way related to the blockchain gas. In the load test, the event handler is running into one of those limitations. Here is a file specifying some of those limits: https://github.com/graphprotocol/graph-node/blob/master/graph/src/runtime/gas/costs.rs For example, the _absolute theoretical max_ would be to save 250k entities in one event handler. 

When looking through the code, I don't think there's any way to override these limits, so self-hosting wouldn't help. It's obviously reasonable for Graph Node put a limit somewhere, and from the load testing we can conclude that up to _like_ 5k subscriptions we're good... 

The question now is whether we go forwards knowing that there clearly is this attack vector. I don't think it matters _too_ much whether the limit is at 2k or 20k or 200k for practical uses. We _could_ still limit the number of subscriber in the protocol to enable this awesome off-chain capability without the attack vector. 

I also wonder how does the current solvency system handles a situation with a 100k subscriber indexes doing updates. I haven't read the code but I'm gonna take a guess that it's going to do 100k calls to get the realtime balance (not for every event though)? There's _probably_ going to exist some DDOS-ing attack vectors here as well...

**Comment by msoni89** [comment]
I think there is a way to set it but the question is do we really need to support that many subscribers or not?

![image](https://user-images.githubusercontent.com/65469737/164529904-7e631575-9332-4d13-a0df-36387dd90a91.png)


![image](https://user-images.githubusercontent.com/65469737/164530140-2b278ed4-db21-455a-bba3-06de5b4da04a.png)

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/164554349-8d519a25-60a2-4f0a-8187-8bd33b8ad467.png)
5000 subcribers

**Comment by hellwolf** [comment]
Also note that you can issue 100 distributions to the same index batched in the same block, and that would only require, say,  at most 1000 subscribers to trigger the issue.

**Comment by hellwolf** [comment]
This is not a good design by abusing current subgraph architecture. We should not bake in undocumented limitations in the system.

Note on solvency model:

Solvency model is aware of this, but since all subscribers get more liquidity as opposed to less, a "lazy evaluation" of checking their balances is an optimization can be done, and is done in our solvency implementations. So there is no scalability issue in the same way in solvency.

**Comment by hellwolf** [comment]
This spike can be considered done, and we will take this findings to the subgraph team.

**Comment by kasparkallas** [comment]
> Also note that you can issue 100 distributions to the same index batched in the same block, and that would only require, say, at most 1000 subscribers to trigger the issue.

The limitation might be per event, not per block. I'll ask in Discord.

**Comment by kasparkallas** [comment]
> Note on solvency model:
> 
> Solvency model is aware of this, but since all subscribers get more liquidity as opposed to less, a "lazy evaluation" of checking their balances is an optimization can be done, and is done in our solvency implementations. So there is no scalability issue in the same way in solvency.

Yep, I get it, probably not an issue here. The solvency sentinel has no rush to account for events that could not affect the balance negatively.

Although the sentinel is probably gonna do a RPC call for all the subscribers _at some point_ to account for the new liquidation date?

> We should not bake in undocumented limitations in the system.

Limitations can be documented and governed.

> This is not a good design by abusing current subgraph architecture.

The way Subgraph does mapping of events is the most common and straight-forward way for any event-sourced system. Going linearly through the events one by one and projecting at the same time. Its also normal for an event to create many entities -- Subgraph has it documented that theoretically 250k is fine -- but obviously as long as Superfluid is boundless then this can be broken and the mapper would stop. There always has to be a solution / fallback for this scenario anyways when going forwards.

### The solution?

Because putting a cap in the protocol seems to be a _definite no go_, we can put a subscriber cap in the Subgraph (we're already counting the subscribers). Once an index hits i.e. 2k subscribers, we stop updating the balances of the subscribers for distributions and stop creating the IndexSubscriptionDistributions. The visualizations and activity history will not be _perfect_ for accounts subscribed to these huge indexes... but who cares (i.e. it's a non-issue)... when it works 99%+ of time and nothing critical depends on it. 

The biggest negative effect of this (or loss of a positive effect) is that when calculating balances, we always have to do a RPC call. If Subgraph had a "perfect history" of balances then we theoretically would not have to rely on RPC calls anymore. RPC calls are what slow down indexing the most.

This would still enable us:
* Subgraph-based solvency sentinel
* Visualizations in products
* Up to date balances in the Subgraph for Ricochet users
* A more natural data model:
  * Would enable querying all account balance affecting activities in one go and have them ordered

**Comment by kasparkallas** [comment]
> > Also note that you can issue 100 distributions to the same index batched in the same block, and that would only require, say, at most 1000 subscribers to trigger the issue.
> 
> The limitation might be per event, not per block. I'll ask in Discord. 

Got a confirmation that it's per event: https://github.com/graphprotocol/graph-node/pull/2414#issuecomment-1108342565
